version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo
    volumes:
      - 'mongo_data:/data/db'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: urls
volumes:
  mongo_data: